fix(setup.cfg)!: require python 3.10
_DataFrame | tuple[_DataFrame, _DataFrame]
TypeError: unsupported operand type(s) for |: 'type' and 'types.GenericAlias'